// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package br.furb.consultor.time;

public final class ClockSystem_Stub
    extends java.rmi.server.RemoteStub
    implements br.furb.consultor.time.IClockSystem, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getDelayConnection_0;
    private static java.lang.reflect.Method $method_getUTCTimeInMillis_1;
    
    static {
	try {
	    $method_getDelayConnection_0 = br.furb.consultor.time.IClockSystem.class.getMethod("getDelayConnection", new java.lang.Class[] {java.lang.String.class});
	    $method_getUTCTimeInMillis_1 = br.furb.consultor.time.IClockSystem.class.getMethod("getUTCTimeInMillis", new java.lang.Class[] {});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ClockSystem_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getDelayConnection(String)
    public java.lang.Long getDelayConnection(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getDelayConnection_0, new java.lang.Object[] {$param_String_1}, -8625854574819575097L);
	    return ((java.lang.Long) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getUTCTimeInMillis()
    public java.lang.Long getUTCTimeInMillis()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getUTCTimeInMillis_1, null, -956981231786620227L);
	    return ((java.lang.Long) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
