// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package br.furb.consultor.venda;

public final class ConsultorVendas_Stub
    extends java.rmi.server.RemoteStub
    implements br.furb.rmi.IConsultorVendas, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getMelhoresOpcoesVendas_0;
    private static java.lang.reflect.Method $method_getMelhoresOpcoesVendasPorBolsa_1;
    private static java.lang.reflect.Method $method_getMelhoresOpcoesVendasPorCliente_2;
    
    static {
	try {
	    $method_getMelhoresOpcoesVendas_0 = br.furb.rmi.IConsultorVendas.class.getMethod("getMelhoresOpcoesVendas", new java.lang.Class[] {});
	    $method_getMelhoresOpcoesVendasPorBolsa_1 = br.furb.rmi.IConsultorVendas.class.getMethod("getMelhoresOpcoesVendasPorBolsa", new java.lang.Class[] {long.class});
	    $method_getMelhoresOpcoesVendasPorCliente_2 = br.furb.rmi.IConsultorVendas.class.getMethod("getMelhoresOpcoesVendasPorCliente", new java.lang.Class[] {long.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ConsultorVendas_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getMelhoresOpcoesVendas()
    public java.util.List getMelhoresOpcoesVendas()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMelhoresOpcoesVendas_0, null, 3455810006555596784L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getMelhoresOpcoesVendasPorBolsa(long)
    public java.util.List getMelhoresOpcoesVendasPorBolsa(long $param_long_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMelhoresOpcoesVendasPorBolsa_1, new java.lang.Object[] {new java.lang.Long($param_long_1)}, -1252963975031698059L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getMelhoresOpcoesVendasPorCliente(long)
    public java.util.List getMelhoresOpcoesVendasPorCliente(long $param_long_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMelhoresOpcoesVendasPorCliente_2, new java.lang.Object[] {new java.lang.Long($param_long_1)}, 7488893827670650057L);
	    return ((java.util.List) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
