package Compras;


/**
* Compras/_CompraStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Terça-feira, 19 de Abril de 2016 20h59min10s BRT
*/

public class _CompraStub extends org.omg.CORBA.portable.ObjectImpl implements Compras.Compra
{

  public void getMelhoresOpcoesCompras (Compras.AcoesCodHolder codigosAcoes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMelhoresOpcoesCompras", true);
                $in = _invoke ($out);
                codigosAcoes.value = Compras.AcoesCodHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMelhoresOpcoesCompras (codigosAcoes        );
            } finally {
                _releaseReply ($in);
            }
  } // getMelhoresOpcoesCompras

  public void getMelhoresOpcoesComprasPorBolsa (int bolsa, Compras.AcoesCodHolder codigosAcoes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMelhoresOpcoesComprasPorBolsa", true);
                $out.write_long (bolsa);
                $in = _invoke ($out);
                codigosAcoes.value = Compras.AcoesCodHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMelhoresOpcoesComprasPorBolsa (bolsa, codigosAcoes        );
            } finally {
                _releaseReply ($in);
            }
  } // getMelhoresOpcoesComprasPorBolsa

  public void getMelhoresOpcoesComprasPorCliente (int codigoCliente, Compras.AcoesCodHolder codigosAcoes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMelhoresOpcoesComprasPorCliente", true);
                $out.write_long (codigoCliente);
                $in = _invoke ($out);
                codigosAcoes.value = Compras.AcoesCodHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMelhoresOpcoesComprasPorCliente (codigoCliente, codigosAcoes        );
            } finally {
                _releaseReply ($in);
            }
  } // getMelhoresOpcoesComprasPorCliente

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Compras/Compra:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _CompraStub
