package Compras;


/**
* Compras/CompraHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Terça-feira, 19 de Abril de 2016 20h59min10s BRT
*/

abstract public class CompraHelper
{
  private static String  _id = "IDL:Compras/Compra:1.0";

  public static void insert (org.omg.CORBA.Any a, Compras.Compra that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Compras.Compra extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Compras.CompraHelper.id (), "Compra");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Compras.Compra read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CompraStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Compras.Compra value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Compras.Compra narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Compras.Compra)
      return (Compras.Compra)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Compras._CompraStub stub = new Compras._CompraStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Compras.Compra unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Compras.Compra)
      return (Compras.Compra)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Compras._CompraStub stub = new Compras._CompraStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
