package Compras;


/**
* Compras/AcoesCodHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Terça-feira, 19 de Abril de 2016 20h59min10s BRT
*/

public final class AcoesCodHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public AcoesCodHolder ()
  {
  }

  public AcoesCodHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Compras.AcoesCodHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Compras.AcoesCodHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Compras.AcoesCodHelper.type ();
  }

}
