package Compras;


/**
* Compras/CompraPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Terça-feira, 19 de Abril de 2016 20h59min10s BRT
*/

public abstract class CompraPOA extends org.omg.PortableServer.Servant
 implements Compras.CompraOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMelhoresOpcoesCompras", new java.lang.Integer (0));
    _methods.put ("getMelhoresOpcoesComprasPorBolsa", new java.lang.Integer (1));
    _methods.put ("getMelhoresOpcoesComprasPorCliente", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Compras/Compra/getMelhoresOpcoesCompras
       {
         Compras.AcoesCodHolder codigosAcoes = new Compras.AcoesCodHolder ();
         this.getMelhoresOpcoesCompras (codigosAcoes);
         out = $rh.createReply();
         Compras.AcoesCodHelper.write (out, codigosAcoes.value);
         break;
       }

       case 1:  // Compras/Compra/getMelhoresOpcoesComprasPorBolsa
       {
         int bolsa = in.read_long ();
         Compras.AcoesCodHolder codigosAcoes = new Compras.AcoesCodHolder ();
         this.getMelhoresOpcoesComprasPorBolsa (bolsa, codigosAcoes);
         out = $rh.createReply();
         Compras.AcoesCodHelper.write (out, codigosAcoes.value);
         break;
       }

       case 2:  // Compras/Compra/getMelhoresOpcoesComprasPorCliente
       {
         int codigoCliente = in.read_long ();
         Compras.AcoesCodHolder codigosAcoes = new Compras.AcoesCodHolder ();
         this.getMelhoresOpcoesComprasPorCliente (codigoCliente, codigosAcoes);
         out = $rh.createReply();
         Compras.AcoesCodHelper.write (out, codigosAcoes.value);
         break;
       }

       case 3:  // Compras/Compra/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Compras/Compra:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Compra _this() 
  {
    return CompraHelper.narrow(
    super._this_object());
  }

  public Compra _this(org.omg.CORBA.ORB orb) 
  {
    return CompraHelper.narrow(
    super._this_object(orb));
  }


} // class CompraPOA
