package Compras;

/**
* Compras/CompraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Terça-feira, 19 de Abril de 2016 20h59min10s BRT
*/

public final class CompraHolder implements org.omg.CORBA.portable.Streamable
{
  public Compras.Compra value = null;

  public CompraHolder ()
  {
  }

  public CompraHolder (Compras.Compra initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Compras.CompraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Compras.CompraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Compras.CompraHelper.type ();
  }

}
